export const API_ENDPOINTS = {
  clinicSignup: "/api/v1/clinics/signup",
  clinicLogin: "/api/v1/clinic-auth/login",
  clinicVerifyOtp: "/api/v1/clinic-auth/verify-otp",
  clinicResendOtp: "/api/v1/clinic-auth/resend-otp",
  authForgotPasswordRequestOtp: "/api/v1/auth/forgot-password/request-otp",
  authForgotPasswordVerifyOtp: "/api/v1/auth/forgot-password/verify-otp",
  authForgotPasswordReset: "/api/v1/auth/forgot-password/reset",
  clinicPlans: "/api/v1/clinic-plans",
  clinicMe: "/api/v1/clinics/me",
  clinicMeSetupStatus: "/api/v1/clinics/me/setup-status",
  clinicMeToday: "/api/v1/clinics/me/today",
  clinicMeAppointments: "/api/v1/clinics/me/appointments",
  clinicMePool: "/api/v1/clinics/me/pool",
  clinicMeRequests: "/api/v1/clinics/me/requests",
  clinicMeDoctors: "/api/v1/clinics/me/doctors",
  clinicMeDoctorInvite: "/api/v1/clinics/me/doctors/invite",
  clinicMeDoctorInvites: "/api/v1/clinics/me/doctors/invites",
  clinicMeServices: "/api/v1/clinics/me/services",
  clinicMeAvailability: "/api/v1/clinics/me/availability",
  clinicMeAnalyticsOverview: "/api/v1/clinics/me/analytics/overview",
  clinicMeAnalyticsAppointments: "/api/v1/clinics/me/analytics/appointments",
  clinicMeAnalyticsDoctors: "/api/v1/clinics/me/analytics/doctors",
  clinicMeAnalyticsPatients: "/api/v1/clinics/me/analytics/patients",
  clinicMeAnalyticsPool: "/api/v1/clinics/me/analytics/pool",
  clinicMeSettingsProfile: "/api/v1/clinics/me/settings/profile",
  clinicMeSettingsSms: "/api/v1/clinics/setup/text-message-notifications",
  clinicMeSettingsFax: "/api/v1/clinics/setup/fax-integration",
  clinicMeSettingsSmtp: "/api/v1/clinics/me/settings/smtp",
  clinicSetupEmailNotifications: "/api/v1/clinics/setup/email-notifications",
  clinicSetupStartAcceptingAppointments: "/api/v1/clinics/setup/start-accepting-appointments",
  clinicMeSettingsCredentials: "/api/v1/clinics/me/settings/credentials",
  clinicMeTeleplanHlth2820: "/api/v1/clinics/me/teleplan-forms/hlth-2820",
  clinicMePaymentHlth2876: "/api/v1/clinics/me/payment-forms/hlth-2876",
  clinicMePhysicianChangeInformation:
    "/api/v1/clinics/me/settings-forms/physician-change-information",
  clinicMeReportDeliveryHl7HealthCareProviderSetup:
    "/api/v1/clinics/me/report-delivery-forms/hl7-health-care-provider-setup",
  doctorInviteDetails: "/api/v1/doctor-auth/invite",
  doctorMe: "/api/v1/doctors/me",
  doctorMeClinics: "/api/v1/doctors/me/clinics",
  doctorMeToday: "/api/v1/doctors/me/today",
  doctorMeAppointments: "/api/v1/doctors/me/appointments",
  doctorMePool: "/api/v1/doctors/me/pool",
  doctorMePatients: "/api/v1/doctors/me/patients",
  doctorMePrescriptions: "/api/v1/doctors/me/prescriptions",
  doctorMeSchedule: "/api/v1/doctors/me/schedule",
  doctorMeSettingsProfile: "/api/v1/doctors/me/settings/profile",
  doctorMeSettingsCredentials: "/api/v1/doctors/me/settings/credentials",
  doctorMeOscarLaunch: "/api/v1/doctors/me/oscar-launch",
  doctorAcceptExistingInvite: "/api/v1/doctor-auth/invite-accept-existing",
  doctorSwitchClinic: "/api/v1/doctor-auth/switch-clinic",
  doctorMeOnboardingHlth2870: "/api/v1/doctors/me/onboarding/payment-forms/hlth-2870",
  doctorMeOnboardingHlth2950: "/api/v1/doctors/me/onboarding/facility-forms/hlth-2950",
  doctorMeOnboardingHlth2832: "/api/v1/doctors/me/onboarding/payment-forms/hlth-2832",
  doctorMeOnboardingTeleplanHlth2820: "/api/v1/doctors/me/onboarding/teleplan-forms/hlth-2820",
  doctorMeOnboardingEnrolmentHlth2991: "/api/v1/doctors/me/onboarding/enrolment-forms/hlth-2991",
  doctorMeSettingsDuplicatePrescriptionPadOrder:
    "/api/v1/doctors/me/onboarding/settings-forms/duplicate-prescription-pad-order",
  patientIntakePhoneStart: "/api/v1/patient-intake/phone/start",
  patientIntakeLocationReverseGeocode: "/api/v1/patient-intake/location/reverse-geocode",
  patientIntakeBimblePharmacies: "/api/v1/patient-intake/pharmacies/bimble",
  patientIntakePhoneVerify: "/api/v1/patient-intake/phone/verify",
  patientIntakeHealth: "/api/v1/patient-intake/health",
  patientIntakeProfile: "/api/v1/patient-intake/profile",
  patientIntakeSlots: "/api/v1/patient-intake/slots",
  patientIntakeVisit: "/api/v1/patient-intake/visit",
  patientIntakeComplete: "/api/v1/patient-intake/complete",
  servicesCatalog: "/api/v1/services",
  mspFeeScheduleSearch: "/api/v1/services/msp-fee-schedule/search",
  mspFeeScheduleSelection: "/api/v1/services/msp-fee-schedule/selection",
  clinicDoctorInvite: "/api/v1/clinics/me/doctors/invite",
  clinicDoctorInvites: "/api/v1/clinics/me/doctors/invites",
} as const;
